"""delete columns profit total_cost from purchase

Revision ID: 0ebc46108432
Revises: 7d65b9e7c999
Create Date: 2026-10-04 19:25:05.861100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ebc46108432'
down_revision: Union[str, Sequence[str], None] = '7d65b9e7c999'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase', 'profit')
    op.drop_column('purchase', 'cost')
    op.add_column('sale', sa.Column('cost', sa.Float(), nullable=False))
    op.add_column('sale', sa.Column('total', sa.Float(), nullable=False))
    op.add_column('sale', sa.Column('profit', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sale', 'profit')
    op.drop_column('sale', 'total')
    op.drop_column('sale', 'cost')
    op.add_column('purchase', sa.Column('cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('purchase', sa.Column('profit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
