"""add colum selling_price sale 

Revision ID: 2912413a9ad9
Revises: 7174f2cf4bfc
Create Date: 2026-10-04 18:44:59.896969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2912413a9ad9'
down_revision: Union[str, Sequence[str], None] = '7174f2cf4bfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
