"""add columns total_cost total profit to sale

Revision ID: 7174f2cf4bfc
Revises: 06b3c3ef239c
Create Date: 2026-10-04 18:43:43.557809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7174f2cf4bfc'
down_revision: Union[str, Sequence[str], None] = '06b3c3ef239c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase', sa.Column('total_cost', sa.Float(), nullable=False))
    op.add_column('purchase', sa.Column('profit', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase', 'profit')
    op.drop_column('purchase', 'total_cost')
    # ### end Alembic commands ###
