"""remove columns total_cost profit from purchase

Revision ID: 7d65b9e7c999
Revises: 34f4bc75af81
Create Date: 2026-10-04 19:13:05.280367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d65b9e7c999'
down_revision: Union[str, Sequence[str], None] = '34f4bc75af81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase', sa.Column('cost', sa.Float(), nullable=False))
    op.drop_column('purchase', 'total_cost')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase', sa.Column('total_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('purchase', 'cost')
    # ### end Alembic commands ###
