"""add id_stock to supplyrequest

Revision ID: 905de4e5be5f
Revises: 
Create Date: 2026-10-04 15:45:00.024937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '905de4e5be5f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplyrequest', sa.Column('id_stock', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'supplyrequest', 'stock', ['id_stock'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'supplyrequest', type_='foreignkey')
    op.drop_column('supplyrequest', 'id_stock')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'part', type_='unique')
    # ### end Alembic commands ###
